spring:
  datasource:
    username: postgres
    password: "{cipher}f5b93392e90a3fcb48143b4d1716dbeef6657df2af5fdb02b00bfbfdd2f48751"
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    info:
      enabled: true

  info:
    env:
      enabled: true
